version: '3'
services:
  # InfluxDB: https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:2.1
    ports:
      - 8069:8069
    volumes:
      - ./storage/influxdb:/var/lib/influxdb2 #this will be mounted
      - ./configs/influx:/etc/influx/
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=trubkacorp
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
      - INFLUXD_CONFIG_PATH=/etc/influx/config.yaml
    restart: on-failure:10
 

